import Header from './components/Header/Header.js'
import Leftbar from './components/Leftbar/Leftbar'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Header></Header>
      <Leftbar></Leftbar>
      {children}
    </div>
  );
}
